In [1]:
import numpy as np


In [2]:
data1 = [1,2,3,4,5]
array1 = np.array(data1)


In [3]:
array1


array([1, 2, 3, 4, 5])

In [4]:
data1

[1, 2, 3, 4, 5]

In [5]:
data2 = [ [1,3,4], [2,5,6]]

In [6]:
data2


[[1, 3, 4], [2, 5, 6]]

In [7]:
array2 = np.array(data2)

In [8]:
array2

array([[1, 3, 4],
       [2, 5, 6]])

In [9]:
array2.dtype


dtype('int32')

In [10]:
# array - no need a loop to cal with loop function
array1

array([1, 2, 3, 4, 5])

In [13]:
array1 + 2

array([3, 4, 5, 6, 7])

In [14]:
array1 * array1

array([ 1,  4,  9, 16, 25])

In [15]:
array1 *2

array([ 2,  4,  6,  8, 10])

In [16]:
array2

array([[1, 3, 4],
       [2, 5, 6]])

In [17]:
array2 + 5


array([[ 6,  8,  9],
       [ 7, 10, 11]])

In [18]:
array2 * 3

array([[ 3,  9, 12],
       [ 6, 15, 18]])

In [19]:
# cut

In [20]:
array2

array([[1, 3, 4],
       [2, 5, 6]])

In [21]:
array2[0]

array([1, 3, 4])

In [22]:
array2[0].dtype

dtype('int32')

In [27]:
array2[0][2]

4

In [28]:
array2.T

array([[1, 2],
       [3, 5],
       [4, 6]])